include:
  - template: Terraform.latest.gitlab-ci.yml

variables:
  # TF_ROOT: ${CI_PROJECT_DIR}/environments/example/production
  TF_ROOT: terraform
  #TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/example-production
  TF_CACHE_KEY: default
  TF_STATE_NAME: default

